name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  analyze_and_test:
    name: Analyze and Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install Dependencies
        run: poetry install

      - name: Run Black
        run: poetry run black --check .

      - name: Run Flake8
        run: poetry run flake8 .

      - name: Run Pylint
        run: poetry run pylint leshy

      - name: Run Mypy
        run: poetry run mypy leshy

      - name: Run Bandit
        run: poetry run bandit -r leshy

      - name: Check Poetry Lock
        run: poetry lock --check

# Will fail if there are no tests. Will be uncommented after adding tests.
#      - name: Run Tests
#        run: poetry run pytest --html=test-report.html --self-contained-html

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-report.html
          if-no-files-found: ignore